### PR TITLE
add the IAM Server ID to the header if present

### PR DESCRIPTION
**Pull request by softcraft-development**

### CODE REVIEW

**Comment by softcraft-development** [comment]
See #20 for the issue which this is meant to address.

**Review by catsby — APPROVED** [review]
LGTM 👍

**Comment by softcraft-development** [comment]
FWIW, I've tested my changes in my own app and it seems to be working well.

**Review by tomhjp — COMMENTED** [review]
Code LGTM, would be good to add a new line to the first table in the readme to document the presence of `VAULT_IAM_SERVER_ID`. If you're able to add that and sign the CLA then I think this is ready to land.

**Comment by softcraft-development** [comment]
>  would be good to add a new line to the first table in the readme to document the presence of VAULT_IAM_SERVER_ID 

Right! I could do that.

> If you're able to add that and sign the CLA then I think this is ready to land.

Signing the CLA is the blocker here. I'll have to get approval from the legal team at my company... and this is going to be a fairly low-priority item for them.

**Comment by softcraft-development** [comment]
I've signed the CLA, so now this is all green!

I also made two further changes:
  * Added documentation for the new header, as requested.
  * Updated the layer version number in the ARNs. I'm not sure what your version number rolling policy is, but I figured I'd take a chance on saving you the hassle! If you'd prefer to do it yourself, let me know and I'll drop the commit.

Note that I've rebased my branch/PR with the latest `main`.

**Comment by tomhjp** [comment]
Awesome! I'll run through a release process that will involve updating the version number separately, but thanks for the thought. Please could you drop that bit? And then I'll merge :)

**Comment by softcraft-development** [comment]
> Please could you drop that bit?

Done! It's all yours now.

**Comment by tomhjp** [comment]
Thanks for the contribution!

**Pull request merged**
